# Test your FastAPI endpoints

### 测试根路径

GET http://127.0.0.1:8000/
Accept: application/json

### 测试say_hello

GET http://127.0.0.1:8000/hello/User
Accept: application/json
Content-Encoding: utf-8

### 测试graphQL

POST 127.0.0.1:8000/graphql
Accept: application/json

query ReadCdasByAdmNo {
    readCdasByAdmNo(admNo: "18284908")
}

